server:
  port: 10020
spring:
  application:
    name: cloud-service-blog-context
    zipkin:
      base-url: http://localhost:10110
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10099/eureka/
