server:
  port: 10010

spring:
  application:
    name: cloud-service-user-context
    zipkin:
      base-url: http://localhost:10110
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/cloud-shop
#    username: postgres
#    password: admin
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 15
#      auto-commit: true
#      idle-timeout: 30000
#      pool-name: DatebookHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10099/eureka/

#mybatis config
#mybatis:
#  mapper-locations: classpath:/mybatis/sqlmap/*.xml,classpath:/mybatis/sqlmap/ext/*.xml
#  config-location: classpath:/mybatis/config/mybatis-config.xml
#  mapper-locations:
#  config-location: classpath:mybatis/config/mybatis-config.xml
