server:
  port: 10100
spring:
  application:
    name: cloud-zuul
  zipkin:
    base-url: http://localhost:10110
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10099/eureka/
zuul:
  routes:
    user:
      path: /v1/user/**
      serviceId: cloud-service-user-context
    blog:
      path: /blog/v1/**
      serviceId: cloud-service-blog-context
    system:
      path: /system/v1/**
      serviceId: cloud-service-system-context
    ccb:
      path: /ccb/v1/**
      serviceId: cloud-service-ccb-context