server:
  port: 10050

spring:
  application:
    name: cloud-webapi
  zipkin:
    base-url: http://localhost:10110

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10099/eureka/