server:
  port: 10040
spring:
  application:
    name: cloud-service-ccb-context
    zipkin:
      base-url: http://localhost:10110
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10099/eureka/
